sudo: required
services:
  - docker

before_install:
  - docker build -t laurentiulbg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true laurentiulbg/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-266186082637"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
